### PR TITLE
removed R from modules to load

### PR DESCRIPTION
**Pull request by b97pla**
Loading R caused a reload of java, switching version from 1.7 to 1.8

### CODE REVIEW

**Comment by b97pla** [comment]
@vezzi @sylvinite @johanherman

**Comment by johanherman** [comment]
@b97pla we don't need R for some plots or reports or something?

**Comment by vezzi** [comment]
some comment for me, are we sure R is not needed... maybe by GATK

**Comment by sylvinite** [comment]
I have no idea what the usage for the R module is/was for either. 
Doing a quick scan of `ngi_pipeline` yields me nothing.
I do suspect the module is mounted in order to follow http://gatkforums.broadinstitute.org/wdl/discussion/2899/howto-install-all-software-packages-required-to-follow-the-gatk-best-practices .

**Comment by sylvinite** [comment]
Also asked Denis about this:
"R is required for a lot of analysis steps. NGI pipeline doesn't necessarily care about R but I would bet piper does. The upcoming RNA-seq pipeline also uses R in several steps."

**Comment by johanherman** [comment]
From what I've heard we're not using the reports that piper can generate which requires R. @b97pla can confirm.

**Comment by b97pla** [comment]
yes, that is what dahlberg claims and we don't use it. There are other steps that can generate plots, e.g. BQSR, but we don't use that either. I haven't tested though, so I can't guarantee anything.

**Comment by sylvinite** [comment]
I'll go ahead and merge this and test it together with the ngi_pipeline PRs. If it works it works. Worst case scenario I'll just roll back this line for the next production release.

**Pull request merged**
