### PR TITLE
Bump sarek and archive_upload_ws

### PR DESCRIPTION
**Pull request by aanil**
* Sarek from v2.6.1 to v2.7
* archive_upload_ws from v1.0.3 to v1.0.4

### CODE REVIEW

**Review by slohse — APPROVED** [review]
:+1:

**Comment by pericsson** [comment]
Should we change the branch from master to monthly? And also merging the master back to monthly?

**Comment by aanil** [comment]
Thank you @pericsson ! The branches sometimes trip me up 😓

**Review by pericsson — APPROVED** [review]
Looks good 👍

**Pull request merged**
