### PR TITLE
Cassandra 2.2.5 doesn't exist, updating to 2.2.6

### PR DESCRIPTION
**Pull request by sylvinite**
Updated cassandra version since 2.2.5 doesn't exist at the source.
If you want to pull 2.2.5 from another source instead, feel free to comment.

### CODE REVIEW

**Comment by johanherman** [comment]
Ugh. I hate it when projects *remove* links! 

Try https://github.com/apache/cassandra/archive/cassandra-2.2.5.zip instead then. The Cassandra db already contains information. I rather not upgrade at the moment, as I'm not sure how it will go.

**Comment by sylvinite** [comment]
No problem. Figured moving to 2.2.6 would probably cause more problems than it'd solve. Reworking it in a minute.

**Comment by johanherman** [comment]
My bad. That was a link to source code. Take this URL instead: http://archive.apache.org/dist/cassandra/2.2.5/apache-cassandra-2.2.5-bin.tar.gz

**Comment by sylvinite** [comment]
I'll just close this for now and let you work it out yourself. That's probably a lot easier than just relaying info to me.

**Pull request merged**
