### PR TITLE
Add uppnex_datadeliver script to be used by funk_004

### PR DESCRIPTION
**Pull request by johanherman**
Script that is used by Uppsala for making manual deliveries into INBOXes. Adds this to our PATH.

### CODE REVIEW

**Comment by sylvinite** [comment]
Looks good, but some questions:

- uppnex_datadeliver is a bash script but lacks suffix?
- Is this necessarily a part of ngi_pipeline?
- {{ root_path }}/sw/ would more intuitively be defined as something generic under host vars?
- Why is {{ root_path }}/sw/ added per site?
- Is this going to be used by stockholm? Else you could move the task a few rows up to implicitly show it's mostly relevant for uppsala.

**Comment by johanherman** [comment]
- Suffixes are pretty much irrelevant. It has been named like this since it started to be used in production by Uppsala on Milou/Nestor a couple of years ago, so to not confuse our bioinformaticians too much it is best to keep it without the suffix. 

- No, it is not necessarily a part of ngi_pipeline. I was considering adding it to the func role first, but we deploy the `sourcme_site` template in the ngi_pipeline so that's why it is more convenient to do it here. 

- Yeah, perhaps we should add a variable for `{{ root_path }}/sw`; it is used like this in many places among our roles. 

- No, it is not supposed to be used by Stockholm. It is only used by Uppsala a couple of months more while we still have the pica mount on irma4; when that disappears a new system for delivering runfolders will be introduced for both Uppsala and Stockholm.

**Comment by johanherman** [comment]
Have added a commit with some changes now.

**Comment by sylvinite** [comment]
Looks good

**Pull request merged**
